## 250126 update(LHC) - Category 3 (question)
question_text: |
    Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field. If the information is not mentioned in the PDF, write `null` (not `None`).
    Fill out in the `null`, `[]` and `{}` values based on the example format:

template: 
    Morphological Properties:
        Particle size: {}
        Particle shape: {}
        Particle distribution: {}
        Coating layer characteristics: {}
        Crystal structure and lattice characteristics: {}