main_question: |
  Below are instructions for filling out items by referring to the examples.
  The values shown to the right of the colon (":") are examples;
  please delete them after reviewing and rewrite them with the values found in the PDF.
  If any item is not mentioned in the PDF, do not remove it—write "None."

question1:
- CAM (Cathode Active Material):
    Stoichiometry information:
      NCM-622:
        Li ratio: "1"
        Ni ratio: "0.6"
        Co ratio: "0.2"
        Mn ratio: "0.2"
        O ratio: "2"
    Commercial NCM: "No"
    Lithium source: "LiOH"
    Synthesis method: "co-precipitation"
    Crystallization method: "Hydrothermal"
    Crystallization temperature: "100°C"
    Crystallization time: "12 hr"
    Doping: "Zr4+ doping"
    Coating: "ZrO2 coating"
    Additional treatment: "None"

question2:
- Electrode (only for coin-cell (half-cell)):
    Active material to Conductive additive to Binder ratio: "90 : 5 : 5"
    Electrolyte: "LiPF6 (EC, EMC, DEC mixture in a 1:1:1 volume ratio)"
    Additive: "FEC 10% addition"
    Electrode thickness: "100 µm"
    Only Cathode Electrode diameter: "14π"
    Loading density (mass loading of NCM): "0.005 g/cm^2"
    Additional treatment for electrode: "None"

question3:
- Morphological results:
    Explanation of SEM results: "Fig. 2a, b; the NCM-622 seems to have more or less a spherical morphology with a diameter of 3–5 µm, composed of densely packed primary particles"
    Explanation of TEM results: "None"

question4:
- Cathode Performance:
    Capacity at all C-rate, mAh/g (with electrode state):
      - 214.5 mAh/g: "@0.1C, ZrO2-coated"
      - 200.8 mAh/g: "@0.5C, ZrO2-coated"
    Voltage range: "2.8–4.3 V"
    Temperature: "Room temperature and 55°C"