## 250126 update(LHC) - Category 1 (question)
question_text: |
  Fill out in the `null`, `[]` and `{}` values based on the example format:

template: 
  CAM (Cathode Active Material): 
    Stoichiometry information: {}
    Commercial NCM used: {}
    Lithium source: null
    Synthesis method: null
    Crystallization method: null
    Crystallization final temperature: null
    Crystallization final duration (hours): null
    Doping: null
    Coating: null