## 250127 update(CSY) - Category 4 (question)
question_text: |
  Fill out in the `null`, `None`, `[]` and `{}` values based on the example format:

template: 
  Cathode Performance: 
    "": 
      - Voltage range: null
        Temperature: null
        C-rate and Specific capacity:
          - C-rate: "0.1"
            Capacity: null
          - C-rate: "0.2"
            Capacity: null
          - C-rate: "0.5"
            Capacity: null
          - C-rate: "1.0"
            Capacity: null
          - C-rate: "2.0"
            Capacity: null
          - Other C-rates and performance:
              - C-rate: null
                Capacity: null