example3:
- Explanation of SEM results: 
	 Particle size: 
	 "{SC-NCM:micron-sized particles, which are about 2μm in diameter}",
	 "{N-NCM:secondary particles are 10-13μm in size}"
	 Particle shape:
	 "{SC-NCM:smooth surfaces}",
	 "{N-NCM:-}"
	 Particle distribution:
	 "{SC-NCM:-}",
	 "{N-NCM:composed of agglomerated primary particles}"
	 Coating layer characteristics:
	 "{NCM-RGO:RGO appears as thin carbon sheets with wrinkled surfaces and folded structures}"
	 
- Explanation of TEM results: 
	 Particle size:
	 "{SC-NCM:approximately 3 μm}",
	 "{N-NCM:-}"
	 Particle shape:
	 "{pristine NCM-811:a well-defined shape without a surface coating layer, and shows surface rupture from nanosized primary particles}"
	 Particle distribution:
	 "{NCM/C:aggregated, uniformly distributed}"
	 Coating layer characteristics:
	 "{M-NCM:a thin Li3PO4 coating layer, approximately 1.8 nm thick, is formed on the surface}",
	 Crystal structure and lattice characteristics: 
	 "{SC-NCM:uniform and clear lattice stripes with a crystal plane spacing of about 0.474 nm, corresponding to the (003) crystal plane of the layered structure}",
	 "{WN92:a layered structure with a space group of R-3m}"