sample_name_searcher: |
  You are an expert assistant specializing in extracting information from research papers related to battery technology. Your role is to carefully analyze the provided document.

  Document:
  {context}

  Question:
  {question}

  Answer:

coordinator_system_prompt: | 




  Below are instructions for filling out items by referring to the examples.
  [
    {
      "CAM (Cathode Active Material)": 
        {
          "Stoichiometry information": {
            "NCM-622": {
              "Li ratio": 1.0,
              "Ni ratio": 0.6,
              "Co ratio": 0.2,
              "Mn ratio": 0.2,
              "O ratio": 2.0
            },
            "ZrO2-NCM-622 (Z622)": {
              "Li ratio": 0.98,
              "Ni ratio": 0.6,
              "Co ratio": 0.2,
              "Mn ratio": 0.2,
              "O ratio": 2.0
            }
          },
          "Commercial NCM used": {
            "NCM-622": "yes",
            "ZrO2-NCM-622 (Z622)": "no"
          },
          "Lithium source": "LiOH",
          "Synthesis method": "co-precipitation",
          "Crystallization method": "Hydrothermal",
          "Crystallization final temperature": 100,
          "Crystallization final duration (hours)": 12,
          "Doping": "Zr4+",
          "Coating": "ZrO2"
        },
      "Electrode (half-cell)": 
        {
          "Active material to Conductive additive to Binder ratio": "90:5:5",
          "Electrolyte": [
              {
                "Salt": "LiPF6",
                "Concentration": "1M",
                "Solvent": "EC:EMC:DEC",
                "Solvent ratio": "1:1:1"
              }
          ],
          "Additive": "FEC, 10%",
          "Loading density (mass loading of NCM)": "5",
        },
      "Morphological Properties": 
        {
          "ParticleSize": {
              "SC-NCM": "micron-sized particles, which are about 2μm in diameter",
              "N-NCM": "secondary particles are 10-13μm in size"
          },
          "ParticleShape": {
              "SC-NCM": "smooth surfaces",
              "N-NCM": null
          },
          "ParticleDistribution": {
              "SC-NCM": null,
              "N-NCM": "composed of agglomerated primary particles"
          },
          "CoatingLayerCharacteristics": {
              "NCM-RGO": "RGO appears as thin carbon sheets with wrinkled surfaces and folded structures"
          },
          "CrystalStructureAndLatticeCharacteristics": {
              "SC-NCM": "uniform and clear lattice stripes with a crystal plane spacing of about 0.474 nm, corresponding to the (003) crystal plane of the layered structure",
              "WN92": "a layered structure with a space group of R-3m"
          }
        },
      "Cathode Performance": 
        {
          "SC-NCM83": [
            {
              "Voltage range": "3.0–4.3",
              "Temperature": 25,
              "C-rate and Specific capacity": [
                {"C-rate": 0.1, "Capacity": null},
                {"C-rate": 0.2, "Capacity": null},
                {"C-rate": 0.5, "Capacity": null},
                {"C-rate": 1.0, "Capacity": 162},
                {"C-rate": 2.0, "Capacity": null},
                {"C-rate": 4.0, "Capacity": null},
                {"Other C-rates and performance": [
                    {"C-rate": 0.05, "Capacity": 199}
                ]}
              ]
            }
          ],
          "pristine NCM": [
            {
              "Voltage range": "3.0-4.3",
              "Temperature": 25,
              "C-rate and Specific capacity": [
                {"C-rate": 0.1, "Capacity": 199.1},
                {"C-rate": 0.2, "Capacity": null},
                {"C-rate": 0.5, "Capacity": null},
                {"C-rate": 1.0, "Capacity": null},
                {"C-rate": 2.0, "Capacity": null},
                {"C-rate": 4.0, "Capacity": 169.8},
                {"Other C-rates and performance": [
                  {"C-rate": 5.0, "Capacity": 159.0},
                  {"C-rate": 6.0, "Capacity": 151.3}
                ]}
              ]
            }
          ]
        }
    }
  ]