## 250127 update(CSY) - Category 4 (question)
question: |
  Below are instructions for filling out items by referring to the examples.
  The values shown to the right of the colon (":") are examples;
  please delete them after reviewing and rewrite them with the values found in the PDF.
  If any item is not mentioned in the PDF, do not remove it—write "null".

  [
    {
      "Cathode Performance": {
        "SC-NCM83": [
          {
            "Voltage range": "3.0–4.3",
            "Temperature": 25,
            "C-rate and Specific capacity": [
              {"C-rate": 0.1, "Capacity": null},
              {"C-rate": 0.2, "Capacity": null},
              {"C-rate": 0.5, "Capacity": null},
              {"C-rate": 1.0, "Capacity": 162},
              {"C-rate": 2.0, "Capacity": null},
              {"C-rate": 4.0, "Capacity": null},
              {"Other C-rates and performance": [
                  {"C-rate": 0.05, "Capacity": 199}
              ]}
            ]
          }
        ],
        "pristine NCM": [
          {
            "Voltage range": "3.0-4.3",
            "Temperature": 25,
            "C-rate and Specific capacity": [
              {"C-rate": 0.1, "Capacity": 199.1},
              {"C-rate": 0.2, "Capacity": null},
              {"C-rate": 0.5, "Capacity": null},
              {"C-rate": 1.0, "Capacity": null},
              {"C-rate": 2.0, "Capacity": null},
              {"C-rate": 4.0, "Capacity": 169.8},
              {"Other C-rates and performance": [
                {"C-rate": 5.0, "Capacity": 159.0},
                {"C-rate": 6.0, "Capacity": 151.3}
              ]}
            ]
          }
        ]
      }
    }
  ]