## 250126 update(LHC) - Category 1 (question)
question: |
  Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field, replacing the placeholders. If the information is not mentioned in the PDF, write "null".

  [
    {
      "CAM (Cathode Active Material)": {
        "Stoichiometry information": {
        },
        "Commercial NCM used": {
        },
        "Lithium source": ,
        "Synthesis method": ,
        "Crystallization method": ,
        "Crystallization final temperature": ,
        "Crystallization final duration (hours)": ,
        "Doping": ,
        "Coating": ,
        "Additional treatment": 
      }
    }
  ]