## 250126 update(LHC) - Category 2 (question)
question_text: |
  Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field. If the information is not mentioned in the PDF, write "null".
  Fill out in the `null`, `None`, `[]` and `{}` values based on the example format:

template: 
  Electrode (half-cell):
    Active material to Conductive additive to Binder ratio: null
    Electrolyte: 
      - 
    Additive: null
    Loading density (mass loading of NCM): null