## 250126 update(LHC) - Category 2 (question)
question_text: |
  Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field. If the information is not mentioned in the PDF, write `null` (not `None`).
  Use all of the NCM cathode sample names (e.g., "NCM-622") provided in the electrochemical performance section.
  Fill out in the `null`, `[]` and `{}` values based on the example format:

template: 
  Electrode (half-cell):
    "":
      - Active material to Conductive additive to Binder ratio: null
      - Electrolyte: 
         - 
      - Additive: null
      - Loading density (mass loading of NCM): null
