## 250126 update(LHC) - Category 2 (question)
question: |
  Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field, replacing the placeholders. If the information is not mentioned in the PDF, write "None".

  [
    {
        "Electrode (half-cell)": {
          "Active material to Conductive additive to Binder ratio": "",
          "Electrolyte": [
          ],
          "Additive": "",
          "Loading density (mass loading of NCM)": "",
          "Additional treatment for electrode": ""
        }
    }
  ]