## 250127 update(CSY) - Category 4 (question)
question: |
  Please fill out the following JSON structure by referring to the PDF. Verify accurate values for each field, replacing the placeholders. If the information is not mentioned in the PDF, write "null".

  [
    {
      "Cathode Performance": {
        "": [
          {
            "Voltage range": ,
            "Temperature": ,
            "C-rate and Specific capacity": [
              {"C-rate": "0.1", "Capacity": },
              {"C-rate": "0.2", "Capacity": },
              {"C-rate": "0.5", "Capacity": },
              {"C-rate": "1.0", "Capacity": },
              {"C-rate": "2.0", "Capacity": },
              {"C-rate": "4.0", "Capacity": },
              {"Other C-rates and performance": [
                {"C-rate": "", "Capacity": }
              ]}
            ]
          }
        ], 
      }
    }
  ]